// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFW97KrY2-DeVoJ6mRm_9_sbRrUWX3WG4',
    appId: '1:248257448444:android:558cb2d6d85653babbca79',
    messagingSenderId: '248257448444',
    projectId: 'nbafantasyapp',
    storageBucket: 'nbafantasyapp.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKHQNFMLGXy0ky2tyMSrMk5pVRuXy-aTk',
    appId: '1:248257448444:web:288008965270b2e3bbca79',
    messagingSenderId: '248257448444',
    projectId: 'nbafantasyapp',
    authDomain: 'nbafantasyapp.firebaseapp.com',
    storageBucket: 'nbafantasyapp.firebasestorage.app',
    measurementId: 'G-VG6WHMENTQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiUosQk5XgSKOjqeQeWjtusXOmmeSZzwM',
    appId: '1:248257448444:ios:bda45363c2de1fdabbca79',
    messagingSenderId: '248257448444',
    projectId: 'nbafantasyapp',
    storageBucket: 'nbafantasyapp.firebasestorage.app',
    iosBundleId: 'com.example.nbaApp2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiUosQk5XgSKOjqeQeWjtusXOmmeSZzwM',
    appId: '1:248257448444:ios:bda45363c2de1fdabbca79',
    messagingSenderId: '248257448444',
    projectId: 'nbafantasyapp',
    storageBucket: 'nbafantasyapp.firebasestorage.app',
    iosBundleId: 'com.example.nbaApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKHQNFMLGXy0ky2tyMSrMk5pVRuXy-aTk',
    appId: '1:248257448444:web:d16d0824b275d110bbca79',
    messagingSenderId: '248257448444',
    projectId: 'nbafantasyapp',
    authDomain: 'nbafantasyapp.firebaseapp.com',
    storageBucket: 'nbafantasyapp.firebasestorage.app',
    measurementId: 'G-S9YSNWQZCH',
  );

}